### ISSUE TITLE
hangs when generating embeddings on supplied vault.txt

### ISSUE THREAD

**Issue by pjbaron** [AllAboutAI-YT/easy-local-rag#14]
WSL2, Windows 10 Pro, Ubuntu 22.04

The localrag.py script will hang indefinitely when processing the supplied vault.txt file.

The problem appears to be that the mxbai-embed-large model hangs when supplied with an empty line (which separate each of the first ~15 sentences in the vault.txt, after these lines, the sentence separators switch from CRLF CRLF to just LF and there are no more empty lines)

I have hack-patched it here with the code:

```
# Generate embeddings for the vault content using Ollama
print(NEON_GREEN + "Generating embeddings for the vault content..." + RESET_COLOR)
vault_embeddings = []
for content in vault_content:
    if (len(content.strip()) > 0):
        print(NEON_GREEN + ">" + content + RESET_COLOR)
        response = ollama.embeddings(model='mxbai-embed-large', prompt=content)
        vault_embeddings.append(response["embedding"])
    else:
        print(NEON_GREEN + "! skip empty line" + RESET_COLOR)
```

**Comment by jwai99** [comment]
thank you this fixed my problem

**Comment by vitorcalvi** [comment]
Traceback (most recent call last):
  File "localrag.py", line 157, in <module>
    response = ollama.embeddings(model='mxbai-embed-large', prompt=content)
  File "/opt/homebrew/anaconda3/envs/RAG2/lib/python3.8/site-packages/ollama/_client.py", line 198, in embeddings
    return self._request(
  File "/opt/homebrew/anaconda3/envs/RAG2/lib/python3.8/site-packages/ollama/_client.py", line 73, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: failed to generate embedding

**Comment by mr250624** [comment]
hey @vitorcalvi , I see the same error as you. Not really looked into it much but I found if you find the line that reads:

`response = ollama.embeddings(model='mxbai-embed-large', prompt=content)`

If I add a 'blank' line before it...it works. So change that one line in localrag.py to:

```
response = ollama.embeddings(model='mxbai-embed-large', prompt='')
response = ollama.embeddings(model='mxbai-embed-large', prompt=content)
```

Like I say I have no idea why and I havent looked into it. I was just debugging..and it worked  :)

**Comment by andresdlp** [comment]
I was having a different error completely. The embeddings were getting "generated" correctly, but when the conversation loop started I would get another error saying that tensor a can't be of size 0 while tensor b is of size 1024. The fix written by @pjbaron worked.

I just had to tweak it so it wouldn't print the entire vault on neon green in the CLI, hehe.
