### ISSUE TITLE
Failed to generate embedding

### ISSUE THREAD

**Issue by 6nagi9** [AllAboutAI-YT/easy-local-rag#9]
Running localrag.py file gives following error.

python localrag_no_rewrite.py 
Traceback (most recent call last):
  File "/Users/eil-its/Documents/experiments/workspace-python/llama3rag/localrag_no_rewrite.py", line 92, in <module>
    response = ollama.embeddings(model='mxbai-embed-large', prompt=content)
  File "/Users/eil-its/Documents/experiments/workspace-python/llama3rag/llama/lib/python3.9/site-packages/ollama/_client.py", line 198, in embeddings
    return self._request(
  File "/Users/eil-its/Documents/experiments/workspace-python/llama3rag/llama/lib/python3.9/site-packages/ollama/_client.py", line 73, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: failed to generate embedding

**Comment by AllAboutAI-YT** [comment]
I cant see any error in code, and it works fine over here. Are you sure you did ollama pull mxbai-embed-large?

**Comment by EdwardDali** [comment]
same error



ollama list
NAME                            ID              SIZE    MODIFIED
mxbai-embed-large:latest        468836162de7    669 MB  3 minutes ago
phi3:instruct                   a2c89ceaed85    2.3 GB  2 days ago


python localrag.py --model 'phi3:instruct'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Git\easy-local-rag\localrag.py", line 130, in <module>
    response = ollama.embeddings(model='mxbai-embed-large', prompt=content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ollama\_client.py", line 198, in embeddings
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ollama\_client.py", line 73, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: failed to generate embedding

**Comment by 6nagi9** [comment]
> I cant see any error in code, and it works fine over here. Are you sure you did ollama pull mxbai-embed-large?

I do have pulled mxbai-embed-large.

```
(llama) (base) eil-its@EIL-ITSs-MacBook-Pro llama3rag % ollama list       
NAME                            ID              SIZE    MODIFIED     
llama3:latest                   a6990ed6be41    4.7 GB  21 hours ago
mistral:latest                  61e88e884507    4.1 GB  19 hours ago
mxbai-embed-large:latest        468836162de7    669 MB  21 hours ago
(llama) (base) eil-its@EIL-ITSs-MacBook-Pro llama3rag % python localrag.py
Traceback (most recent call last):
  File "/Users/eil-its/Documents/experiments/workspace-python/llama3rag/localrag.py", line 130, in <module>
    response = ollama.embeddings(model='mxbai-embed-large', prompt=content)
  File "/Users/eil-its/Documents/experiments/workspace-python/llama3rag/llama/lib/python3.9/site-packages/ollama/_client.py", line 198, in embeddings
    return self._request(
  File "/Users/eil-its/Documents/experiments/workspace-python/llama3rag/llama/lib/python3.9/site-packages/ollama/_client.py", line 73, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: failed to generate embedding
(llama) (base) eil-its@EIL-ITSs-MacBook-Pro llama3rag % 
```
